
/* 1. 컨트롤 템플릿 추가 (011-전역버튼1) */
INSERT INTO META_TEMPLATE
SELECT 'BTNCTL011T'
      , TYPE1
      , TYPE2
      , '011' AS TYPE3
      , '전역버튼1'
      , '<span class="ub-control button global etc1" id="@id@" @auth_type@ @functionAlias@ @class@ @height@ @onclick@ @ondblclick@ @onfocus@ @tooltip@ @value@ @width@>
    <a href="#none" title="@label@">@label@</a>
</span>'
      , '전역버튼1'
      , PROJECTNAME
      , STATUS
      , '2015-08-12'
      , REGUSER
      , '2015-08-12'
      , LASTUSER
 FROM META_TEMPLATE      
WHERE TEMPLATEID = 'BTNCTL009T';

/* 1. 컨트롤 템플릿 추가 (012-전역버튼2) */
INSERT INTO META_TEMPLATE
SELECT 'BTNCTL012T'
      , TYPE1
      , TYPE2
      , '012' AS TYPE3
      , '전역버튼2'
      , '<span class="ub-control button global etc2" id="@id@" @auth_type@ @functionAlias@ @class@ @height@ @onclick@ @ondblclick@ @onfocus@ @tooltip@ @value@ @width@>
    <a href="#none" title="@label@">@label@</a>
</span>'
      , '전역버튼2'
      , PROJECTNAME
      , STATUS
      , '2015-08-12'
      , REGUSER
      , '2015-08-12'
      , LASTUSER
 FROM META_TEMPLATE      
WHERE TEMPLATEID = 'BTNCTL009T';

/* 1. 컨트롤 템플릿 추가 (013-전역버튼3) */
INSERT INTO META_TEMPLATE
SELECT 'BTNCTL013T'
      , TYPE1
      , TYPE2
      , '013' AS TYPE3
      , '전역버튼3'
      , '<span class="ub-control button global etc3" id="@id@" @auth_type@ @functionAlias@ @class@ @height@ @onclick@ @ondblclick@ @onfocus@ @tooltip@ @value@ @width@>
    <a href="#none" title="@label@">@label@</a>
</span>'
      , '전역버튼3'
      , PROJECTNAME
      , STATUS
      , '2015-08-12'
      , REGUSER
      , '2015-08-12'
      , LASTUSER
 FROM META_TEMPLATE      
WHERE TEMPLATEID = 'BTNCTL009T';

/* 1. 컨트롤 템플릿 추가 (014-전역버튼4) */
INSERT INTO META_TEMPLATE
SELECT 'BTNCTL014T'
      , TYPE1
      , TYPE2
      , '014' AS TYPE3
      , '전역버튼4'
      , '<span class="ub-control button global etc4" id="@id@" @auth_type@ @functionAlias@ @class@ @height@ @onclick@ @ondblclick@ @onfocus@ @tooltip@ @value@ @width@>
    <a href="#none" title="@label@">@label@</a>
</span>'
      , '전역버튼4'
      , PROJECTNAME
      , STATUS
      , '2015-08-12'
      , REGUSER
      , '2015-08-12'
      , LASTUSER
 FROM META_TEMPLATE      
WHERE TEMPLATEID = 'BTNCTL009T';

/* 1. 컨트롤 템플릿 추가 (015-전역버튼5) */
INSERT INTO META_TEMPLATE
SELECT 'BTNCTL015T'
      , TYPE1
      , TYPE2
      , '015' AS TYPE3
      , '전역버튼5'
      , '<span class="ub-control button global etc5" id="@id@" @auth_type@ @functionAlias@ @class@ @height@ @onclick@ @ondblclick@ @onfocus@ @tooltip@ @value@ @width@>
    <a href="#none" title="@label@">@label@</a>
</span>'
      , '전역버튼5'
      , PROJECTNAME
      , STATUS
      , '2015-08-12'
      , REGUSER
      , '2015-08-12'
      , LASTUSER
 FROM META_TEMPLATE      
WHERE TEMPLATEID = 'BTNCTL009T';

/* 1. 컨트롤 템플릿 추가 (016-전역버튼6) */
INSERT INTO META_TEMPLATE
SELECT 'BTNCTL016T'
      , TYPE1
      , TYPE2
      , '016' AS TYPE3
      , '전역버튼6'
      , '<span class="ub-control button global etc6" id="@id@" @auth_type@ @functionAlias@ @class@ @height@ @onclick@ @ondblclick@ @onfocus@ @tooltip@ @value@ @width@>
    <a href="#none" title="@label@">@label@</a>
</span>'
      , '전역버튼6'
      , PROJECTNAME
      , STATUS
      , '2015-08-12'
      , REGUSER
      , '2015-08-12'
      , LASTUSER
 FROM META_TEMPLATE      
WHERE TEMPLATEID = 'BTNCTL009T';

/* 1. 컨트롤 템플릿 추가 (017-전역버튼7) */
INSERT INTO META_TEMPLATE
SELECT 'BTNCTL017T'
      , TYPE1
      , TYPE2
      , '017' AS TYPE3
      , '전역버튼7'
      , '<span class="ub-control button global etc7" id="@id@" @auth_type@ @functionAlias@ @class@ @height@ @onclick@ @ondblclick@ @onfocus@ @tooltip@ @value@ @width@>
    <a href="#none" title="@label@">@label@</a>
</span>'
      , '전역버튼7'
      , PROJECTNAME
      , STATUS
      , '2015-08-12'
      , REGUSER
      , '2015-08-12'
      , LASTUSER
 FROM META_TEMPLATE      
WHERE TEMPLATEID = 'BTNCTL009T';

/* 1. 컨트롤 템플릿 추가 (018-전역버튼8) */
INSERT INTO META_TEMPLATE
SELECT 'BTNCTL018T'
      , TYPE1
      , TYPE2
      , '018' AS TYPE3
      , '전역버튼8'
      , '<span class="ub-control button global etc8" id="@id@" @auth_type@ @functionAlias@ @class@ @height@ @onclick@ @ondblclick@ @onfocus@ @tooltip@ @value@ @width@>
    <a href="#none" title="@label@">@label@</a>
</span>'
      , '전역버튼8'
      , PROJECTNAME
      , STATUS
      , '2015-08-12'
      , REGUSER
      , '2015-08-12'
      , LASTUSER
 FROM META_TEMPLATE      
WHERE TEMPLATEID = 'BTNCTL009T';


/* 2. 컨트롤 타입 추가 */
INSERT INTO META_CONTROL_TYPE SELECT TYPE, 'BUTTON-GLOBAL1', 'BTNCTL011T', '전역버튼1', '전역버튼1', EXTENDCLASS, STATUS, '2015-08-12', REGUSER, '2015-08-12', LASTUSER FROM META_CONTROL_TYPE WHERE TEMPLATEID = 'BTNCTL009T';
INSERT INTO META_CONTROL_TYPE SELECT TYPE, 'BUTTON-GLOBAL2', 'BTNCTL012T', '전역버튼2', '전역버튼2', EXTENDCLASS, STATUS, '2015-08-12', REGUSER, '2015-08-12', LASTUSER FROM META_CONTROL_TYPE WHERE TEMPLATEID = 'BTNCTL009T';
INSERT INTO META_CONTROL_TYPE SELECT TYPE, 'BUTTON-GLOBAL3', 'BTNCTL013T', '전역버튼3', '전역버튼3', EXTENDCLASS, STATUS, '2015-08-12', REGUSER, '2015-08-12', LASTUSER FROM META_CONTROL_TYPE WHERE TEMPLATEID = 'BTNCTL009T';
INSERT INTO META_CONTROL_TYPE SELECT TYPE, 'BUTTON-GLOBAL4', 'BTNCTL014T', '전역버튼4', '전역버튼4', EXTENDCLASS, STATUS, '2015-08-12', REGUSER, '2015-08-12', LASTUSER FROM META_CONTROL_TYPE WHERE TEMPLATEID = 'BTNCTL009T';
INSERT INTO META_CONTROL_TYPE SELECT TYPE, 'BUTTON-GLOBAL5', 'BTNCTL015T', '전역버튼5', '전역버튼5', EXTENDCLASS, STATUS, '2015-08-12', REGUSER, '2015-08-12', LASTUSER FROM META_CONTROL_TYPE WHERE TEMPLATEID = 'BTNCTL009T';
INSERT INTO META_CONTROL_TYPE SELECT TYPE, 'BUTTON-GLOBAL6', 'BTNCTL016T', '전역버튼6', '전역버튼6', EXTENDCLASS, STATUS, '2015-08-12', REGUSER, '2015-08-12', LASTUSER FROM META_CONTROL_TYPE WHERE TEMPLATEID = 'BTNCTL009T';
INSERT INTO META_CONTROL_TYPE SELECT TYPE, 'BUTTON-GLOBAL7', 'BTNCTL017T', '전역버튼7', '전역버튼7', EXTENDCLASS, STATUS, '2015-08-12', REGUSER, '2015-08-12', LASTUSER FROM META_CONTROL_TYPE WHERE TEMPLATEID = 'BTNCTL009T';
INSERT INTO META_CONTROL_TYPE SELECT TYPE, 'BUTTON-GLOBAL8', 'BTNCTL018T', '전역버튼8', '전역버튼8', EXTENDCLASS, STATUS, '2015-08-12', REGUSER, '2015-08-12', LASTUSER FROM META_CONTROL_TYPE WHERE TEMPLATEID = 'BTNCTL009T';

/* 3. 폴더 파일 맵핑 */
INSERT INTO META_FOLDER_FILE(FOLDER_ID, FILE_ID1, FILE_ID2, FOLDER_TYPE, PROJECT_ID)VALUES('9', 'BTN', 'BUTTON-GLOBAL1', 'CONTROL', 'P000000002');
INSERT INTO META_FOLDER_FILE(FOLDER_ID, FILE_ID1, FILE_ID2, FOLDER_TYPE, PROJECT_ID)VALUES('9', 'BTN', 'BUTTON-GLOBAL2', 'CONTROL', 'P000000002');
INSERT INTO META_FOLDER_FILE(FOLDER_ID, FILE_ID1, FILE_ID2, FOLDER_TYPE, PROJECT_ID)VALUES('9', 'BTN', 'BUTTON-GLOBAL3', 'CONTROL', 'P000000002');
INSERT INTO META_FOLDER_FILE(FOLDER_ID, FILE_ID1, FILE_ID2, FOLDER_TYPE, PROJECT_ID)VALUES('9', 'BTN', 'BUTTON-GLOBAL4', 'CONTROL', 'P000000002');
INSERT INTO META_FOLDER_FILE(FOLDER_ID, FILE_ID1, FILE_ID2, FOLDER_TYPE, PROJECT_ID)VALUES('9', 'BTN', 'BUTTON-GLOBAL5', 'CONTROL', 'P000000002');
INSERT INTO META_FOLDER_FILE(FOLDER_ID, FILE_ID1, FILE_ID2, FOLDER_TYPE, PROJECT_ID)VALUES('9', 'BTN', 'BUTTON-GLOBAL6', 'CONTROL', 'P000000002');
INSERT INTO META_FOLDER_FILE(FOLDER_ID, FILE_ID1, FILE_ID2, FOLDER_TYPE, PROJECT_ID)VALUES('9', 'BTN', 'BUTTON-GLOBAL7', 'CONTROL', 'P000000002');
INSERT INTO META_FOLDER_FILE(FOLDER_ID, FILE_ID1, FILE_ID2, FOLDER_TYPE, PROJECT_ID)VALUES('9', 'BTN', 'BUTTON-GLOBAL8', 'CONTROL', 'P000000002');

/* 4. 컨트롤 속성 */
INSERT INTO META_CONTROL_TYPE_ATTRIBUTE SELECT TYPE, 'BUTTON-GLOBAL1', ATTRIBUTE, SECTIONCLASS, PARSETYPE, MANDATORY, VALUECLASS, INITVALUE, DESCRIPTION, STATUS, FIXEDATTR  FROM META_CONTROL_TYPE_ATTRIBUTE WHERE TYPE = 'BTN' AND TYPEDEF='BUTTON-BASIC' AND ATTRIBUTE NOT IN ('ico', 'location');
INSERT INTO META_CONTROL_TYPE_ATTRIBUTE SELECT TYPE, 'BUTTON-GLOBAL2', ATTRIBUTE, SECTIONCLASS, PARSETYPE, MANDATORY, VALUECLASS, INITVALUE, DESCRIPTION, STATUS, FIXEDATTR  FROM META_CONTROL_TYPE_ATTRIBUTE WHERE TYPE = 'BTN' AND TYPEDEF='BUTTON-BASIC' AND ATTRIBUTE NOT IN ('ico', 'location');
INSERT INTO META_CONTROL_TYPE_ATTRIBUTE SELECT TYPE, 'BUTTON-GLOBAL3', ATTRIBUTE, SECTIONCLASS, PARSETYPE, MANDATORY, VALUECLASS, INITVALUE, DESCRIPTION, STATUS, FIXEDATTR  FROM META_CONTROL_TYPE_ATTRIBUTE WHERE TYPE = 'BTN' AND TYPEDEF='BUTTON-BASIC' AND ATTRIBUTE NOT IN ('ico', 'location');
INSERT INTO META_CONTROL_TYPE_ATTRIBUTE SELECT TYPE, 'BUTTON-GLOBAL4', ATTRIBUTE, SECTIONCLASS, PARSETYPE, MANDATORY, VALUECLASS, INITVALUE, DESCRIPTION, STATUS, FIXEDATTR  FROM META_CONTROL_TYPE_ATTRIBUTE WHERE TYPE = 'BTN' AND TYPEDEF='BUTTON-BASIC' AND ATTRIBUTE NOT IN ('ico', 'location');
INSERT INTO META_CONTROL_TYPE_ATTRIBUTE SELECT TYPE, 'BUTTON-GLOBAL5', ATTRIBUTE, SECTIONCLASS, PARSETYPE, MANDATORY, VALUECLASS, INITVALUE, DESCRIPTION, STATUS, FIXEDATTR  FROM META_CONTROL_TYPE_ATTRIBUTE WHERE TYPE = 'BTN' AND TYPEDEF='BUTTON-BASIC' AND ATTRIBUTE NOT IN ('ico', 'location');
INSERT INTO META_CONTROL_TYPE_ATTRIBUTE SELECT TYPE, 'BUTTON-GLOBAL6', ATTRIBUTE, SECTIONCLASS, PARSETYPE, MANDATORY, VALUECLASS, INITVALUE, DESCRIPTION, STATUS, FIXEDATTR  FROM META_CONTROL_TYPE_ATTRIBUTE WHERE TYPE = 'BTN' AND TYPEDEF='BUTTON-BASIC' AND ATTRIBUTE NOT IN ('ico', 'location');
INSERT INTO META_CONTROL_TYPE_ATTRIBUTE SELECT TYPE, 'BUTTON-GLOBAL7', ATTRIBUTE, SECTIONCLASS, PARSETYPE, MANDATORY, VALUECLASS, INITVALUE, DESCRIPTION, STATUS, FIXEDATTR  FROM META_CONTROL_TYPE_ATTRIBUTE WHERE TYPE = 'BTN' AND TYPEDEF='BUTTON-BASIC' AND ATTRIBUTE NOT IN ('ico', 'location');
INSERT INTO META_CONTROL_TYPE_ATTRIBUTE SELECT TYPE, 'BUTTON-GLOBAL8', ATTRIBUTE, SECTIONCLASS, PARSETYPE, MANDATORY, VALUECLASS, INITVALUE, DESCRIPTION, STATUS, FIXEDATTR  FROM META_CONTROL_TYPE_ATTRIBUTE WHERE TYPE = 'BTN' AND TYPEDEF='BUTTON-BASIC' AND ATTRIBUTE NOT IN ('ico', 'location');
