UPDATE SYS_CODE
   SET CODE_CATEGORY_ID = 'APMD_'||CODE_CATEGORY_ID
where CODE_CATEGORY_ID IN (
	'CALL_TYPE', 'CODE_CATEGORY', 'FUNCTION_ALIAS',	'FUNCTION_TYPE', 'LAYOUT_TYPE',	'MASK_LIST', 
	'PROJECT_CODE',	'QUERY_TYPE', 'SCREEN_TYPE', 'SCREEN_VIEW_TYPE', 'SERVICE_TYPE'
);

UPDATE SYS_CODE_CATEGORY
   SET CODE_CATEGORY_ID = 'APMD_'||CODE_CATEGORY_ID
     , CODE_CATEGORY_NM = '[APMD]'||CODE_CATEGORY_NM
where CODE_CATEGORY_ID IN (
	'CALL_TYPE', 'CODE_CATEGORY', 'FUNCTION_ALIAS',	'FUNCTION_TYPE', 'LAYOUT_TYPE',	'MASK_LIST', 
	'PROJECT_CODE',	'QUERY_TYPE', 'SCREEN_TYPE', 'SCREEN_VIEW_TYPE', 'SERVICE_TYPE'
);

UPDATE AP_SERVICE_CODE
   SET ALIAS = 'APMD_'||ALIAS
     , CODE_CATEGORY_ID = 'APMD_'||CODE_CATEGORY_ID
where CODE_CATEGORY_ID IN (
	'CALL_TYPE', 'CODE_CATEGORY', 'FUNCTION_ALIAS',	'FUNCTION_TYPE', 'LAYOUT_TYPE',	'MASK_LIST', 
	'PROJECT_CODE',	'QUERY_TYPE', 'SCREEN_TYPE', 'SCREEN_VIEW_TYPE', 'SERVICE_TYPE'
);

COMMIT;