ALTER TABLE SYS_BOARD_ARTICLE
MODIFY(ID_ARTICLE VARCHAR2(50 BYTE));


ALTER TABLE SYS_BOARD_ARTICLE
MODIFY(NO_GROUP VARCHAR2(50 BYTE));


ALTER TABLE SYS_BOARD_ARTICLE
MODIFY(ID_PARENT_ARTICLE VARCHAR2(50 BYTE));


ALTER TABLE SYS_BOARD_ARTICLE
 ADD (NO_ARTICLE  VARCHAR2(50));


COMMENT ON COLUMN SYS_BOARD_ARTICLE.ID_ARTICLE IS '게시물 ID';

COMMENT ON COLUMN SYS_BOARD_ARTICLE.NO_ARTICLE IS '게시물번호';


ALTER TABLE SYS_BOARD_INQUIRY_HISTORY
MODIFY(ID_ARTICLE VARCHAR2(50 BYTE));

COMMENT ON COLUMN SYS_BOARD_INQUIRY_HISTORY.ID_ARTICLE IS '게시물 ID';


ALTER TABLE SYS_BOARD_EVALUATION
MODIFY(ID_ARTICLE VARCHAR2(50 BYTE));

COMMENT ON COLUMN SYS_BOARD_EVALUATION.ID_ARTICLE IS '게시물 ID';


ALTER TABLE SYS_BOARD_REPLY
MODIFY(ID_ARTICLE VARCHAR2(50 BYTE));


ALTER TABLE SYS_BOARD_REPLY
MODIFY(ID_REPLY VARCHAR2(50 BYTE));


ALTER TABLE SYS_BOARD_REPLY
MODIFY(NO_GROUP VARCHAR2(50));


ALTER TABLE SYS_BOARD_REPLY
MODIFY(ID_PARENT_REPLY VARCHAR2(50 BYTE));

COMMENT ON COLUMN SYS_BOARD_REPLY.ID_ARTICLE IS '게시물 ID';

COMMENT ON COLUMN SYS_BOARD_REPLY.ID_REPLY IS '댓글 ID';


ALTER TABLE SYS_BOARD_ARTICLE_SHARE
MODIFY(ID_ARTICLE VARCHAR2(50 BYTE));

COMMENT ON COLUMN SYS_BOARD_ARTICLE_SHARE.ID_ARTICLE IS '게시물 ID';
