


--INSERT
WITH T AS(
SELECT A.TABLE_NAME,A.COLUMN_NAME,A.COLUMN_ID,C.LV,'  /* '||B.COMMENTS ||'*/'AS COMMENTS
FROM USER_TAB_COLUMNS A, USER_COL_COMMENTS B,
(SELECT LEVEL LV FROM DUAL CONNECT BY LEVEL <=2 ) C
WHERE A.TABLE_NAME = 'TB_VOC_CLASS'
AND A.TABLE_NAME = B.TABLE_NAME AND A.COLUMN_NAME = B.COLUMN_NAME)
SELECT DESCRIPTION
FROM (
--INSERT INTO
SELECT 
    CASE WHEN COLUMN_ID = 1 THEN 'INSERT INTO '||TABLE_NAME ||'(
    ' 
    END||
    CASE WHEN COLUMN_ID = 1 THEN '' ELSE ', ' END 
    || COLUMN_NAME || '  ' ||COMMENTS ||
    CASE WHEN COLUMN_ID = MAX(COLUMN_ID) OVER (PARTITION BY TABLE_NAME) THEN--ROW_NUMBER() OVER (ORDER BY COLUMN_ID DESC) THEN     
    '
    )' 
    END DESCRIPTION,
    LV,COLUMN_ID 
FROM T
WHERE LV = 1
--VALUES
UNION ALL
SELECT 
    CASE WHEN COLUMN_ID = 1 THEN 'VALUES ('||
    '
    #{' 
    END||
    CASE WHEN COLUMN_ID = 1 THEN '' ELSE ', #{' END 
    || COLUMN_NAME ||'}'|| '  ' ||COMMENTS ||
    CASE WHEN COLUMN_ID = MAX(COLUMN_ID) OVER (PARTITION BY TABLE_NAME) THEN
    '
    )
            ' 
    END,
    LV,COLUMN_ID
FROM T 
WHERE LV=2
ORDER BY LV,COLUMN_ID ) 



--UPDATE
WITH T AS(
SELECT A.TABLE_NAME,A.COLUMN_NAME,A.COLUMN_ID,C.LV,'  /*'||B.COMMENTS ||'*/'AS COMMENTS
FROM USER_TAB_COLUMNS A, USER_COL_COMMENTS B,
(SELECT LEVEL LV FROM DUAL CONNECT BY LEVEL <=2 ) C
WHERE A.TABLE_NAME = 'TB_VOC_CLASS'
AND A.TABLE_NAME = B.TABLE_NAME AND A.COLUMN_NAME = B.COLUMN_NAME)
SELECT A,B,C
FROM (
SELECT 
    CASE WHEN COLUMN_ID = 1 THEN 'UPDATE '||TABLE_NAME 
    ||'
SET
    ' 
    END||
    CASE WHEN COLUMN_ID = 1 THEN '' ELSE ', ' END 
    || COLUMN_NAME AS A,
     '=' AS B,
    CASE WHEN COLUMN_ID = 1 THEN 
    '#{' 
    END||
    CASE WHEN COLUMN_ID = 1 THEN '' ELSE '#{' END 
    || COLUMN_NAME ||'}'|| '  ' ||COMMENTS AS C,
    LV,COLUMN_ID 
FROM T 
WHERE LV=1
UNION ALL
SELECT 
    CASE WHEN COLUMN_ID = 1 THEN 
    'WHERE
    ' 
    END||
    CASE WHEN COLUMN_ID = 1 THEN '' ELSE ', ' END 
    || COLUMN_NAME AS A,
     '=' AS B,
    CASE WHEN COLUMN_ID = 1 THEN 
    '#{' 
    END||
    CASE WHEN COLUMN_ID = 1 THEN '' ELSE '#{' END 
    || COLUMN_NAME ||'}'|| '  ' ||COMMENTS AS C,
    LV,COLUMN_ID
FROM T 
WHERE LV=2
ORDER BY LV,COLUMN_ID )




--DELETE
WITH T AS(
SELECT C.TABLE_NAME,C.COLUMN_NAME,POSITION, '  /*'||D.COMMENTS ||'*/'AS COMMENTS
FROM USER_CONSTRAINTS A, USER_CONS_COLUMNS B, USER_TAB_COLUMNS C, USER_COL_COMMENTS D
 WHERE A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
 AND B.TABLE_NAME = C.TABLE_NAME AND B.COLUMN_NAME = C.COLUMN_NAME  
 AND B.TABLE_NAME = D.TABLE_NAME AND B.COLUMN_NAME = D.COLUMN_NAME
 AND A.TABLE_NAME = 'TB_VOC_CLASS'
 AND A.CONSTRAINT_TYPE = 'P')
SELECT A||B||C
FROM (
SELECT 
    CASE WHEN POSITION = 1 THEN 'DELETE FROM '||TABLE_NAME 
    ||'
WHERE
    ' 
    END||
    CASE WHEN POSITION = 1 THEN '' ELSE ', ' END 
    || COLUMN_NAME AS A,
     '=' AS B,
    CASE WHEN POSITION = 1 THEN 
    '#{' 
    END||
    CASE WHEN POSITION = 1 THEN '' ELSE '#{' END 
    || COLUMN_NAME ||'}'|| '  ' ||COMMENTS  AS C,
    POSITION COLUMN_ID 
FROM T 
ORDER BY COLUMN_ID )





--SELECT
WITH T AS(
SELECT A.TABLE_NAME,A.COLUMN_NAME,A.COLUMN_ID,C.LV,'  /* '||B.COMMENTS ||'*/'AS COMMENTS
FROM USER_TAB_COLUMNS A, USER_COL_COMMENTS B,
(SELECT LEVEL LV FROM DUAL CONNECT BY LEVEL <=2 ) C
WHERE A.TABLE_NAME = 'TBS_VOC_CLASS'
AND A.TABLE_NAME = B.TABLE_NAME AND A.COLUMN_NAME = B.COLUMN_NAME)
SELECT DESCRIPTION
 FROM (
--SELECT
SELECT 
    CASE WHEN COLUMN_ID = 1 THEN 'SELECT '
    END||
    CASE WHEN COLUMN_ID = 1 THEN '' ELSE ', ' END 
    || COLUMN_NAME || '  ' ||COMMENTS ||
    CASE WHEN COLUMN_ID = MAX(COLUMN_ID) OVER (PARTITION BY TABLE_NAME) THEN--ROW_NUMBER() OVER (ORDER BY COLUMN_ID DESC) THEN     
    '
    FROM '||TABLE_NAME 
    END DESCRIPTION,
    LV,COLUMN_ID 
FROM T
WHERE LV = 1 
UNION ALL
SELECT 
    CASE WHEN COLUMN_ID = 1 THEN 
    'WHERE
    ' 
    END||
    CASE WHEN COLUMN_ID = 1 THEN '' ELSE ', ' END 
    || COLUMN_NAME ||
     '=' ||
    CASE WHEN COLUMN_ID = 1 THEN 
    '#{' 
    END||
    CASE WHEN COLUMN_ID = 1 THEN '' ELSE '#{' END 
    || COLUMN_NAME ||'}'|| '  ' ||COMMENTS AS C,
    LV,COLUMN_ID
FROM T 
WHERE LV=2
ORDER BY LV,COLUMN_ID  )